### ISSUE TITLE
Firebase credentials

### ISSUE THREAD

**Issue by Berkmann18** [u12206050/gridsome-source-firestore#8]
Is still impossible to get this to work with the normal Firebase configuration?
If not, would there be a way to use a single piece of information from the AdminSDK (say API key to facilitate CI/CD pipelines)?

**Comment by u12206050** [comment]
You can generate and download the Firebase configuration file: https://firebase.google.com/docs/admin/setup#initialize-sdk

**Comment by Berkmann18** [comment]
I already know I can download the Admin firebase configuration file, but since I'm trying to avoid to push the _full_ AdminSDK file to a repo, it's not a viable solution.
The thing is that I'm using TravisCI which builds the app which would need the AdminSDK file which as you rightly put in the README, shouldn't be pushed to a repo.
I guess this plugin can handle having the `GOOGLE_APPLICATION_CREDENTIALS` environment variable (which points to the content of the file) instead of `require('./..-firebase-adminsdk-....json')`?

Also, did Firebase not get back to you on the "support for handling custom service accounts"? Is there anything I could help with?

_**EDIT**_: Yes, I did try to change to code to use `admin.credential.applicationDefault()` (with `GOOGLE_APPLICATION_CREDENTIALS` pointing to the _location_ of the file on my computer) as follows:
```js
const admin = require('firebase-admin');
const {db} = require('gridsome-source-firestore');

module.exports = {
  plugins: [
    {
      use: 'gridsome-source-firestore',
      options: {
        credentials: admin.credential.applicationDefault(),
  //...
```
But that lead to the following error:
```
Error: Certificate object must contain a string "private_key" property.
   at FirebaseAppError.FirebaseError [as constructor] (/home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/firebase-admin/lib/utils/error.js:42:28)
    at FirebaseAppError.PrefixedFirebaseError [as constructor] (/home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/firebase-admin/lib/utils/error.js:88:28)
    at new FirebaseAppError (/home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/firebase-admin/lib/utils/error.js:123:28)
    at new Certificate (/home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/firebase-admin/lib/auth/credential.js:118:19)
    at new CertCredential (/home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/firebase-admin/lib/auth/credential.js:187:64)
    at Object.cert (/home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/firebase-admin/lib/firebase-namespace.js:220:58)
    at new FirestoreSource (/home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/gridsome-source-firestore/index.js:40:36)
    at Plugins.initialize (/home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/gridsome/lib/app/Plugins.js:61:11)
    at App.init (/home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/gridsome/lib/app/App.js:120:18)
    at App.bootstrap (/home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/gridsome/lib/app/App.js:49:16)
    at module.exports (/home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/gridsome/lib/app/index.js:12:18)
    at module.exports (/home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/gridsome/lib/develop.js:20:21)
    at /home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/gridsome/index.js:44:12
    at Command.<anonymous> (/home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/gridsome/index.js:13:44)
    at Command.listener (/home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:203:13)
```

On the other hand, using `require(process.env.GOOGLE_APPLICATION_CREDENTIALS)` seems to work more but it still requires the file to be there.

That being said, having the content of the JSON file as the value of the variable (read `GOOGLE_APPLICATION_CREDENTIALS`) and using `JSON.parse(process.env.GOOGLE_APPLICATION_CREDENTIALS)` seems to be the way to go.

**Comment by hacknug** [comment]
> That being said, having the content of the JSON file as the value of the variable (read `GOOGLE_APPLICATION_CREDENTIALS`) and using `JSON.parse(process.env.GOOGLE_APPLICATION_CREDENTIALS)``seems to be the way to go.

This is also the approach I'm using on one of my sites via netlify-cli:
```js
credentials: JSON.parse(process.env.FIREBASE_SDK),
```
